// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function ApplicationMenu():Promise<menu.Menu>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile():Promise<string>;

export function SaveFile(arg1:string):Promise<void>;

export function SaveToFile(arg1:string,arg2:string):Promise<void>;
